/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PIdRouteImport } from './routes/p.$id'
import { Route as ApiCoverFilenameRouteImport } from './routes/api/cover.$filename'
import { Route as ApiAudioFilenameRouteImport } from './routes/api/audio.$filename'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PIdRoute = PIdRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoverFilenameRoute = ApiCoverFilenameRouteImport.update({
  id: '/api/cover/$filename',
  path: '/api/cover/$filename',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAudioFilenameRoute = ApiAudioFilenameRouteImport.update({
  id: '/api/audio/$filename',
  path: '/api/audio/$filename',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/p/$id': typeof PIdRoute
  '/api/audio/$filename': typeof ApiAudioFilenameRoute
  '/api/cover/$filename': typeof ApiCoverFilenameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/p/$id': typeof PIdRoute
  '/api/audio/$filename': typeof ApiAudioFilenameRoute
  '/api/cover/$filename': typeof ApiCoverFilenameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/p/$id': typeof PIdRoute
  '/api/audio/$filename': typeof ApiAudioFilenameRoute
  '/api/cover/$filename': typeof ApiCoverFilenameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/p/$id' | '/api/audio/$filename' | '/api/cover/$filename'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/p/$id' | '/api/audio/$filename' | '/api/cover/$filename'
  id:
    | '__root__'
    | '/'
    | '/p/$id'
    | '/api/audio/$filename'
    | '/api/cover/$filename'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PIdRoute: typeof PIdRoute
  ApiAudioFilenameRoute: typeof ApiAudioFilenameRoute
  ApiCoverFilenameRoute: typeof ApiCoverFilenameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$id': {
      id: '/p/$id'
      path: '/p/$id'
      fullPath: '/p/$id'
      preLoaderRoute: typeof PIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cover/$filename': {
      id: '/api/cover/$filename'
      path: '/api/cover/$filename'
      fullPath: '/api/cover/$filename'
      preLoaderRoute: typeof ApiCoverFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audio/$filename': {
      id: '/api/audio/$filename'
      path: '/api/audio/$filename'
      fullPath: '/api/audio/$filename'
      preLoaderRoute: typeof ApiAudioFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PIdRoute: PIdRoute,
  ApiAudioFilenameRoute: ApiAudioFilenameRoute,
  ApiCoverFilenameRoute: ApiCoverFilenameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
